#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Sima
"""

# standart library import
import logging
import sys

from importlib import __import__
from os.path import isfile, basename
##

# third parties components
##

# local import
from sima import core
from sima.plugins.crop import Crop
from sima.plugins.addhist import History
from sima.lib.logger import set_logger
from sima.lib.simadb import SimaDB
from sima.utils.config import ConfMan
from sima.utils.startopt import StartOpt
from sima.utils.utils import exception_log
##

# official plugins to start
PLUGINS = (Crop, History)


def load_contrib_plugins(sima):
    """Handles contrib/external plugins
    """
    if not sima.config.has_option('sima', 'plugins'):
        return
    logger = logging.getLogger('sima')
    for plugin in sima.config.get('sima','plugins').split(','):
        plugin = plugin.strip(' \n')
        module = 'sima.plugins.contrib.{}'.format(plugin.lower())
        try:
            mod_obj = __import__(module, fromlist=[plugin])
        except ImportError as err:
            logger.error('Failed to load plugin\'s module: {0} ({1})'.format(module, err))
            sima.shutdown()
        try:
            plugin_obj = getattr(mod_obj, plugin)
        except AttributeError as err:
            logger.error('Failed to load plugin {0} ({1})'.format(plugin, err))
            sima.shutdown()
        logger.info('Loading contrib plugin: {name} ({doc})'.format(**plugin_obj.info()))
        sima.register_plugin(plugin_obj)


def main():
    """Entry point, deal w/ CLI and starts application
    """
    info = dict({'version': core.__version__,})
    # StartOpt gathers options from command line call (in StartOpt().options)
    sopt = StartOpt(info)
    # set logger
    verbosity = sopt.options.get('verbosity', 'warning')
    cli_loglevel = getattr(logging, verbosity.upper())
    set_logger(level=verbosity)
    logger = logging.getLogger('sima')
    logger.setLevel(cli_loglevel)
    # loads configuration
    conf_manager = ConfMan(logger, sopt.options)
    config = conf_manager.config
    logger.setLevel(getattr(logging,
                    config.get('log', 'verbosity').upper()))  # pylint: disable=E1103

    logger.debug('Command line say: {0}'.format(sopt.options))

    # Create Database
    if (sopt.options.get('create_db', None)
       or not isfile(conf_manager.db_file)):
        logger.info('Creating database in "{}"'.format(conf_manager.db_file))
        open(conf_manager.db_file, 'a').close()
        SimaDB(db_path=conf_manager.db_file).create_db()
        if sopt.options.get('create_db', None):
            logger.info('Done, bye...')
            sys.exit(0)

    logger.info('Starting...')
    sima = core.Sima(config, conf_manager.db_file)

    #  Loading internal plugins
    for plugin in PLUGINS:
        logger.info('Loading internal plugin: {name} ({doc})'.format(**plugin.info()))
        sima.register_plugin(plugin)

    #  Loading contrib plugins
    load_contrib_plugins(sima)
    try:
        sima.run()
    except KeyboardInterrupt:
        logger.info('Caught KeyboardInterrupt, stopping')
        sima.shutdown()


# Script starts here
if __name__ == '__main__':
    # pylint: disable=broad-except
    try:
        main()
    except Exception:
        exception_log()


# VIM MODLINE
# vim: ai ts=4 sw=4 sts=4 expandtab
