'\" t
.\"     Title: simadb_cli
.\"    Author: Jack Kaliko <kaliko@azylum.org>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 02/12/2017
.\"    Manual: mpd-sima 0.14.3 User Manual
.\"    Source: mpd-sima
.\"  Language: English
.\"
.TH "SIMADB_CLI" "1" "02/12/2017" "mpd-sima" "mpd-sima 0.14.3 User Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
simadb_cli \- simadb_cli is a command line interface editor for the sima user DB\&.
.SH "SYNOPSIS"
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR \fB\-\-remove_artist=\fR\fIartist\fR [\fB\-\-dbfile=\fR\fIdb_file\fR] [\fB\-\-reciprocal\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR \fB\-\-purge_hist\fR [\fB\-\-dbfile=\fR\fIdb_file\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR \fB\-\-view_all\fR [\fB\-\-dbfile=\fR\fIdb_file\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR {\fB\-\-bl_curr_trk\fR | \fB\-\-bl_curr_art\fR | \fB\-\-bl_curr_alb\fR | \fB\-\-bl_art=\fR\fIartist_name\fR} [\fB\-\-dbfile=\fR\fIdb_file\fR] [\fB\-\-host=\fR\fImpd_host\fR] [\fB\-\-port=\fR\fImpd_port\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR \fB\-\-remove_bl=\fR\fIrow_id\fR [\fB\-\-dbfile=\fR\fIdb_file\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR \fB\-\-view_bl\fR [\fB\-\-dbfile=\fR\fIdb_file\fR]
.HP \w'\fBsimadb_cli\fR\ 'u
\fBsimadb_cli\fR {{\fB\-h\fR\ |\ \fB\-\-help\fR} | \fB\-\-version\fR}
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBsimadb_cli\fR
commands\&.
.PP
simadb_cli is a command line interface to get and edit users blacklist database used with MPD_sima\&. The default database file (see
the section called \(lqFILES\(rq) can be overridden if you want\&.
.SH "EXAMPLE"
.SS "Black list edition"
.PP
\fIAdding to black list\&.\fR
You can add a single track, an album or an artist to the black list\&. The element to black list is chosen from the currently playing track\&. Use
\fB\-\-bl_curr_trk\fR
to prevent simadb_cli to queue this track,
\fB\-\-bl_curr_alb\fR
or
\fB\-\-bl_curr_art\fR
respectively for the album and the artist\&.
.PP
Remember you need access to your MPD server to retrieve information to black list\&. Defaults are localhost:6600 or found in environment variables but you may set it up from command line:
.PP
\fBsimadb_cli \-\-bl_curr_art \-S mympd\&.example\&.org\fR
.PP
\fITo black list a specific artist\fR
(not currently playing) you can use
\fB\-\-bl_ar="Artist name to black list"\fR\&.
.SH "OPTIONS"
.PP
The program follows the usual GNU command line syntax, with long options starting with two dashes ("\-")\&. A summary of options is included below\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Print help and exit\&.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version and exit\&.
.RE
.PP
\fB\-\-bl_art=\fR\fB\fIartist_name\fR\fR
.RS 4
Use to black list
\fIartist_name\fR\&. simadb_cli is checking
\fIartist_name\fR
is actually in MPD music library (cf
\fB\-S\fR
and
\fB\-P\fR
options to set MPD host/address if necessary)\&.
.sp
If
\fIartist_name\fR
is not found the script print out a list of matching artists\&.
.RE
.PP
\fB\-\-bl_curr_trk\fR | \fB\-\-bl_curr_art\fR | \fB\-\-bl_curr_alb\fR
.RS 4
Use to black list the currently playing track|artist|album\&. You need access to your MPD server, use
\fB\-S\fR
and
\fB\-P\fR
to set MPD host/address if necessary\&.
.RE
.PP
\fB\-d \fR\fB\fIdb_file\fR\fR, \fB\-\-dbfile=\fR\fB\fIdb_file\fR\fR
.RS 4
Use the specific file
\fIdb_file\fR
as database\&.
.br
Default is too use
\fBXDG_DATA_HOME\fR
(see
the section called \(lqFILES\(rq)\&.
.RE
.PP
\fB\-\-purge_hist\fR
.RS 4
Purge history, you may supply an alternative DB file with \-\-dbfile option\&.
.RE
.PP
\fB\-\-remove_bl=\fR\fB\fIrow_id\fR\fR
.RS 4
Use to remove a black list entry\&. To get the row_id to suppress use
\fB\-\-view_bl\fR
option\&.
.RE
.PP
\fB\-\-view_bl\fR
.RS 4
Get all entries in the black list\&.
.RE
.PP
\fB\-P \fR\fB\fImpd_port\fR\fR, \fB\-\-port=\fR\fB\fImpd_port\fR\fR
.RS 4
Use the specific port number
\fImpd_port\fR
on MPD server\&. This overrides
\fBMPD_PORT\fR
environment variable\&.
.br
Default is
\fI6600\fR\&.
.RE
.PP
\fB\-S \fR\fB\fImpd_host\fR\fR, \fB\-\-host=\fR\fB\fImpd_host\fR\fR
.RS 4
Use the specific host
\fImpd_host\fR
as MPD server\&.
.br
\fImpd_host\fR
can be an
IP
or a fully qualified domain name as long as your system can resolve it\&. This overrides
\fBMPD_HOST\fR
environment variable\&.
.br
Default is
\fIlocalhost\fR\&.
.RE
.SH "FILES"
.PP
${XDG_DATA_HOME}/mpd_sima/sima\&.db
.RS 4
SQLite DB file\&. Usually
\fBXDG_DATA_HOME\fR
is set to
${HOME}/\&.local/share\&.
.RE
.SH "FEEDBACK/BUGS"
.PP
The maintainer would be more than happy to ear from you, don\*(Aqt hesitate to send feedback,
\m[blue]\fB\%http://kaliko.me/id/\fR\m[]\&.
.PP
XMPP
users are welcome to join the dedicated chat room at
\m[blue]\fBkaliko\&.me@conf\&.azylum\&.org\fR\m[]\&.
.SH "SEE ALSO"
.PP
\fBmpc\fR(1),
\fBmpd\fR(1)
.PP
/usr/share/doc/mpd\-sima/
.SH "AUTHOR"
.PP
\fBJack Kaliko\fR <\&kaliko@azylum\&.org\&>
.RS 4
Wrote this man page and is currently leading MPD_sima project\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2009-2017 Jack Kaliko
.br
.PP
This manual page was written for the Debian system (and may be used by others)\&.
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 3 published by the Free Software Foundation\&.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in
/usr/share/common\-licenses/GPL\&.
.sp
